version: '3.8'

services:
  java-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASS: mypass
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysqldata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  mysqldata:

